import "@/styles/globals.css";

import { Drawer, DrawerContent, DrawerTrigger } from "@/components/ui/drawer";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import Providers from "@/lib/Providers";
import DynamicUserButton from "./DynamicUserButton";
import { BurgerIcon } from "@/components/ui/icons";
import NavLinks from "./NavLinks";
import { DialogTitle } from "@radix-ui/react-dialog";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Providers>
          <TRPCReactProvider>
            <div className="h-lvh">
              <nav className="flex h-[15%] items-center justify-between px-3 py-6">
                <Link href={"/"}>
                  <h1 className="text-lg text-white">Petrzalka</h1>
                </Link>
                <div className="sm:hidden">
                  <Drawer>
                    <DrawerTrigger>
                      <BurgerIcon size={20} className="text-white" />
                    </DrawerTrigger>
                    <DrawerContent className="gap-2">
                      <DialogTitle></DialogTitle>
                      <div className="flex flex-col">
                        <NavLinks />
                      </div>
                    </DrawerContent>
                  </Drawer>
                </div>
                <DynamicUserButton />
              </nav>
              <main className="h-[85%]">{children}</main>
            </div>
          </TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}
